"""Builds data/wordlist.json (the builder's project format, schema 2) from
data/themes.txt and the generated batches in data/gen/words/*.json.

Theme ids, frequency lookups and word filters follow app.js, so the file opens in the
builder exactly as if the words had been added there.
"""
import collections, glob, json, math, os, re, unicodedata

ROOT = os.path.join(os.path.dirname(__file__), '..')
KINDS = {'place', 'property', 'wordplay'}

def slug(t):
    t = unicodedata.normalize('NFKD', t)
    t = ''.join(c for c in t if not unicodedata.combining(c))
    return re.sub(r'[^\w]+|_+', '_', t, flags=re.U).strip('_').lower()

# ---- themes, in file order (as the app imports them)
themes, at, stack = [], {}, []
for raw in open(os.path.join(ROOT, 'data', 'themes.txt'), encoding='utf-8'):
    if not raw.strip(): continue
    ind = (len(raw) - len(raw.lstrip(' '))) // 2
    body, note = (raw.strip().split(' -- ', 1) + [''])[:2]
    tags = re.findall(r'\[([^\]]+)\]', body)
    name = re.sub(r'\s*\[[^\]]+\]', '', body).strip()
    group = name.endswith(':'); name = name.rstrip(':').strip()
    while stack and stack[-1][0] >= ind: stack.pop()
    parent = stack[-1][1] if stack else -1
    base = slug(name) or 'theme'; tid, k = base, 2
    while tid in at: tid = f'{base}_{k}'; k += 1
    kind = next((t for t in tags if t in KINDS), '')
    region = next((t.split(':', 1)[1].strip() for t in tags if t.startswith('region:')), '')
    themes.append([tid, name, '', parent, 1 if group else 0, kind, region, 0, note.strip(), {}, 1 if 'adult' in tags else 0, 1 if 'separate' in tags else 0])
    at[tid] = len(themes) - 1
    stack.append((ind, len(themes) - 1))
by_name = {t[1]: i for i, t in enumerate(themes)}

# ---- frequency list, as zipf() in app.js
FREQ = {}
for line in open(os.path.join(ROOT, 'data', 'freq-en.txt'), encoding='utf-8'):
    parts = line.split(); z = int(parts[0]) / 10
    for w in parts[1:]: FREQ[w] = z
def zipf(t):
    parts = [p for p in re.split(r'[ -]+', t.lower()) if p]
    inv = 0
    for p in parts:
        if p not in FREQ: return None
        inv += 1 / 10 ** (FREQ[p] - 9)
    return round(math.log10(1 / inv) + 9, 1) if parts else None

# ---- filters, as filterReason() in app.js with default settings
def reason(t):
    c = re.sub(r'[ -]', '', t); parts = re.split(r'[ -]+', t)
    if not re.fullmatch(r'[^\W\d_]+', c): return 'characters'
    if len(parts) > 2: return 'more than two words'
    if len(c) < 3 or len(c) > 20: return 'length'
    return ''

# ---- words
words = collections.OrderedDict()
forms = collections.defaultdict(collections.Counter)
flags, missing = [], []
for path in sorted(glob.glob(os.path.join(ROOT, 'data', 'gen', 'words', 'batch-*.json'))):
    for tname, v in json.load(open(path, encoding='utf-8')).items():
        ti = by_name.get(tname)
        if ti is None: missing.append(tname); continue
        if v.get('flag'): flags.append(f'{tname}: {v["flag"]}')
        setno = {}
        for n, s in enumerate(v.get('sets') or [], 1):
            for x in s: setno[x.lower()] = n
        for text, uk, fam, z10, adult in v['words']:
            text = re.sub(r'\s+', ' ', text.strip()); uk = re.sub(r'\s+', ' ', (uk or '').strip())
            k = slug(text)
            if not k: continue
            forms[k][text] += 1
            w = words.setdefault(k, {'th': [], 'fam': {}, 'uk': '', 'ze': [], 'adult': 0, 'notes': []})
            if ti not in w['th']: w['th'].append(ti)
            w['fam'][ti] = min(w['fam'].get(ti, 5), int(fam)) if ti in w['fam'] else int(fam)
            if uk and uk.lower() != text.lower() and not w['uk']: w['uk'] = uk
            w['ze'].append(int(z10)); w['adult'] |= int(adult)
            if text.lower() in setno: w['notes'].append(f'anagram set {setno[text.lower()]}')

rows, n_est = [], 0
for k, w in words.items():
    c = forms[k]
    text = max(c, key=lambda f: (c[f], f == f.lower()))  # most common form; lowercase on ties (turkey vs Turkey)
    z = zipf(text); zu = zipf(w['uk']) if w['uk'] else None
    z = max(x for x in (z, zu) if x is not None) if (z is not None or zu is not None) else None
    ze = round(sorted(w['ze'])[len(w['ze']) // 2] / 10, 1)  # median estimate
    estimated = z is None or bool(re.search(r'[ -]', text))
    if estimated: z = ze  # multi-word names: estimate for the whole name (see wordZipf in app.js)
    zest = ze
    n_est += estimated
    r = reason(text)
    note = '; '.join(dict.fromkeys([r] + w['notes'] if r else w['notes']))
    rows.append([text, w['th'], 0 if r else 1, round(z * 10) if z else 0, 0, 'L', note, w['uk'],
                 [], 0, [], [[t, f] for t, f in w['fam'].items()], round(zest * 10) if zest else 0, w['adult']])

out = {
    'schema': 2, 'app': 'wordlist-builder', 'saved': 'generated by tools/build_wordlist.py',
    'themeFields': ['id', 'name', 'label', 'parent', 'group', 'kind', 'region', 'difficulty', 'note', 'sourceTerms', 'adult', 'separate'],
    'themes': themes,
    'wordFields': ['text', 'themes', 'enabled', 'zipf10', 'difficulty', 'sources', 'note', 'uk', 'clashes', 'checked', 'suggestions',
                   'familiarity', 'zipfEstimate10', 'adult'],
    'words': rows,
}
json.dump(out, open(os.path.join(ROOT, 'data', 'wordlist.json'), 'w', encoding='utf-8'), ensure_ascii=False, separators=(',', ':'))

play = [i for i, t in enumerate(themes) if not t[4]]
count = collections.Counter(t for r in rows for t in r[1])
print(f'{len(themes)} themes ({len(play)} playable), {len(rows)} words, {sum(len(r[1]) for r in rows)} links, '
      f'{sum(1 for r in rows if not r[2])} disabled by filters, {n_est} with estimated frequency')
print('playable themes with no words yet:', sum(1 for i in play if not count[i]))
print('playable themes under 12 words:', sum(1 for i in play if 0 < count[i] < 12))
if missing: print('UNKNOWN theme names in batches:', missing[:20])
open(os.path.join(ROOT, 'data', 'gen', 'words', 'flags.txt'), 'w', encoding='utf-8').write('\n'.join(flags) + '\n')
print(len(flags), 'flagged themes (data/gen/words/flags.txt)')
